version: "3.9"

services:
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn core.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
      - ./static/:/app/static/
    expose:
      - "8000"
    networks:
      - main
    restart: on-failure

  nginx:
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/app/static/
      




networks:
  main:
